version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flyspray
      - POSTGRES_USER=flyspray
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

  flyspray:
    image: flyspray
    restart: always
    ports:
      - 8080:80
    volumes:
      - flyspray:/var/www/html
    environment:
      - POSTGRES_HOST=db:5432
      - POSTGRES_DB=flyspray
      - POSTGRES_USER=flyspray
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - DB_PREFIX=flyspray_
      - FS_ADMIN_USERNAME=admin
      - FS_ADMIN_EMAIL=admin@example.com
      - FS_ADMIN_PASSWORD_FILE=/run/secrets/fs_admin_password
    depends_on:
      - db
    secrets:
      - db_password
      - fs_admin_password

  cron:
    image: flyspray
    restart: always
    volumes:
      - flyspray:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db

secrets:
  db_password:
    file: db_password.txt
  fs_admin_password:
    file: fs_admin_password.txt

volumes:
  db:
  flyspray:
